version: "3.5"
services:
  nginx:
    image: jenkins-nginx
    build:
      context: .
      dockerfile: NginxDockerfile
    ports:
    - 443:443
  master:
    image: jenkins-master
    build:
      context: .
      dockerfile: MasterDockerfile
  slave:
    image: jenkins-slave
    build:
      context: .
      dockerfile: SlaveDockerfile